#!/bin/bash

set -eu

if [ $# -ne 3 ]; then
	echo "usage: build <name> <source_dir> <build_dir>"
	exit 1
fi

if [ ! -d $2 ]; then
	echo "$1 is not a directory"
	exit 1
fi

if [ -d $3 ]; then
	echo "$3 already exists"
	exit 1
fi

mkdir $3

cd $2
find . -name "*.pyc" -delete
zip -r build.zip *
cd ..
mv $2/build.zip $3/

cat << HEADER > $3/$1
#! /usr/bin/env python

HEADER

cat $3/build.zip >> $3/$1
chmod +x $3/$1

mkdir $3/$1-mac
cp -r lib-mac $3/$1-mac/lib
cp $3/$1 $3/$1-mac/

mkdir $3/$1-linux-32-bit
cp -r lib-linux-32-bit $3/$1-linux-32-bit/lib
cp $3/$1 $3/$1-linux-32-bit/

mkdir $3/$1-linux-64-bit
cp -r lib-linux-64-bit $3/$1-linux-64-bit/lib
cp $3/$1 $3/$1-linux-64-bit/

if [ -d extra ]; then
	cp extra/* $3/$1-mac/
	cp extra/* $3/$1-linux-32-bit/
	cp extra/* $3/$1-linux-64-bit/
fi

